{{- range $name, $secret := .Values.secrets }}
{{- if $secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
type: Opaque
{{- if $secret.stringData }}
stringData:
{{- range $key, $value := $secret.stringData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- else }}
stringData: {}
{{- end }}
---
{{- end }}
{{- end }}
